package tet.oleg_zhabko.tsp.datas;

import android.content.Context;

import java.util.StringTokenizer;

import tet.oleg_zhabko.tsp.ThisApp;
import tet.tetlibrarymodules.alldbcontroller.AllDatabaseController;
import tet.tetlibrarymodules.tetdebugutils.debug.debug_tools.ShowlongLargeString;
import tet.tetlibrarymodules.tetdebugutils.debug.debug_tools.TetDebugUtil;

public class addDemoDatas {
    private String pseudo_tag = addDemoDatas.class.getSimpleName();
    private String db_name;
    private Context context;

    private String queryPoints = "CREATE TABLE IF NOT EXISTS owner_points (point_id INTEGER PRIMARY KEY AUTOINCREMENT, organisation_name VARCHAR (50), zone VARCHAR (100), folder_color VARCHAR (50), sales_name VARCHAR (50), phone_number VARCHAR (50), point_owner VARCHAR (50), latitude REAL, longitude REAL, landmarks VARCHAR (150), description VARCHAR (50), phone_ambar VARCHAR (50), description_office VARCHAR (350), work_from_h VARCHAR (10), work_from_m VARCHAR (10), work_to_h VARCHAR (10), work_to_m VARCHAR (10), strike_from_h VARCHAR (10), strike_from_m VARCHAR (10), strike_to_h VARCHAR (10), strike_to_m VARCHAR (10), color VARCHAR (50), pin_icon_code INTEGER, color1 VARCHAR (50));\n";
    private String queryPoints1 = "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Генадий Мясов', '096-783-6172', 'Бака А.А', 50.59912074927432, 27.61044770479202, 'с. Мхайленки', 'Золотой лев,магазин', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Звягин', '71b300', 'Ирина Рудь', '', 'Быкова', 49.951521, 29.0869423, 'No dada', 'No data', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ( 'РУДЬ', 'Звягин', '71b300', 'Ирина Рудь', '', 'Бака', 50.59912074927432, 27.61044770479202, 'Золотой лев', 'Магазин за углом дома', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Генадий Мясов', '', 'Батиньска', 50.41721820414725, 27.72315010428429, 'Конти', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Генадий Мясов', '', 'Данильчук', 50.59685209774468, 27.62035310268402, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Генадий Мясов', '', 'Иванчук', 50.58970704637681, 27.62906827032566, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ( 'Мясовита', 'Звягин', '71b300', 'Генадий Мясов', '', 'Кирилюк', 50.55719921518457, 27.61899240949036, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Генадий Мясов', '', 'Кравченко', 50.5735933, 27.6305685, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ( 'Мясовита', 'Звягин', '71b300', 'Генадий Мясов', '', 'Леонтьева', 50.29495790145062, 27.67897243576734, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ( 'Мясовита', 'Звягин', '71b300', 'Генадий Мясов', '', 'Мидаичук', 50.58926281270886, 27.6294581964612, 'Медведь', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Ольга Мясов', '', 'Найдюк', 50.5942049156366, 27.59993679821491, 'Продукты', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Ольга Мясов', '', 'Науметова', 50.5867469704617, 27.61391948908567, 'Свет продуктов', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n";
    private String queryPoints2 = "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Ольга Мясов', '', 'Наумьетова', 50.58978963463687, 27.64020178467035, 'Сонти', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Ольга Мясов', '', 'Павлушенко', 50.58635954563216, 27.62521125376225, 'МираМакс', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Ольга Мясов', '', 'Повальчук', 50.58224242772191, 27.60154444724321, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Анатолий Монак', '', 'Повальчук', 50.58937626617163, 27.59785808622837, '', 'Склад', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Анатолий Монак', '', 'Семенюк', 50.55246350636176, 27.6469874382019, '', 'За угловым домом', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Анатолий Монак', '', 'Симчук', 50.5972664646807, 27.63887912034988, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Анатолий Монак', '', 'Скаковьскка', 50.66521834710991, 27.62667406350375, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Анатолий Монак', '', 'Сябрук', 50.2950319, 27.6715592, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Галина Монак', '', 'Федорова', 50.5918319451335, 27.5989842787385, '', 'Продукты', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Галина Монак', '', 'Хомееча', 50.5892331, 27.6196668, '', 'Троя', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Звягин', '71b300', 'Галина Монак', '', 'Шкабара', 50.57341708617849, 27.62716490775347, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Ольга Мясов', '', 'Шулявитская', 50.61469936018683, 27.63660953305867, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Звягин', '71b300', 'Ольга Мясов', '', 'Ющенкко', 50.58970142397884, 27.61395979939468, '', 'Напротив ворот парка, газбанк, вход левый торец', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Бердичев-1', '71b300', 'Светлана Монак', '', 'Лизогубенко', 49.9504571, 28.8674786, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Бердичев-1', '71b300', 'Светлана Монак', '', 'Маркер 1', 49.9000018, 28.5927986, '', 'Бердичев, Одесская 70а', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Бердичев-1', '71b300', 'Светлана Монак', '', 'Маркер 2', 49.89482986021731, 28.59181199222803, '', 'Бердичев Братьев Михеевых 1твой продуктовый', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Бердичев-1', '71b300', 'Светлана Монак', '', 'Маркер 3', 49.1000018, 28.1000018, '', 'Бердичев Володарского 70', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Бердичев-1', '71b300', 'Галина Монак', '', 'Маркер 4', 49.2000018, 28.2000018, '', 'Бердичев, Сосниной 102 корпус2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Бердичев-1', '71b300', 'Галина Монак', '', 'Маркер 5', 49.3000018, 28.3000018, '', 'село Быстрик ул.Шевченко 1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Бердичев-1', '71b300', 'Галина Монак', '', 'Маркер 6', 49.4000018, 28.1000018, '', 'Бердичев, Маложитомирская 4/1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Бердичев-1', '71b300', 'Галина Монак', '', 'Маркер 7', 49.5000018, 28.1000018, '', 'Бердичев, Одесская 58А', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Бердичев-1', '71b300', 'Ирина Рудь', '', 'Маркер 8', 49.4000018, 28.1000018, '', 'Бердичев,30лет Победы 2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Бердичев-1', '71b300', 'Ирина Рудь', '', 'Маркер 9', 49.4000018, 28.1000018, '', 'Гришковцы, Житомирская 72', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Бердичев-1', '71b300', 'Ирина Рудь', '', 'Маркер 10', 49.8494000018, 28.1000018, '', 'Бердичев, Ленина 40', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Бердичев-1', '71b300', 'Ирина Рудь', '', 'Маркер 11', 49.94000018, 28.1000018, '', 'Бердичев, Мучная 32', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Бердичев-1', '71b300', 'Генадий Рудь', '', 'Маркер 12', 49.104000018, 28.1000018, '', 'Бердичев, Червоная 1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Бердичев-1', '71b300', 'Генадий Мясов', '', 'Маркер 13', 49.114000018, 28.1000018, '', 'Бердичев, Газопроводная 23', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Бердичев-1', '71b300', 'Генадий Мясов', '', 'Маркер 14', 49.124000018, 28.1000018, '', 'Бердичев, Житомирская 20', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Бердичев-1', '71b300', '', '', 'Маркер 14', 49.134000018, 28.1000018, '', 'Бердичев, Здоровья 1/42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Бердичев-1', '71b300', '', '', 'Настюк', 49.85396309998195, 28.74817630000401, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n";
    private String queryPoints3 = "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Бердичев-1', '71b300', 'Ольга Мясов', '', 'Янчук', 49.85494182282871, 28.74729015364552, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Житомир', '71b300', 'Ольга Мясов', '', 'Батиньска', 50.41721820414725, 27.72315010428429, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Казатин', '71b300', 'Ольга Мясов', '', 'Ааниликп', 49.96172602166731, 28.87051241792733, '', 'Рынок', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Казатин', '71b300', 'Ольга Мясов', '', 'Адамович', 49.7363933, 28.9433617, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Казатин', '71b300', 'Ольга Мясов', '', 'Адамович', 49.7155533, 28.83449, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Петр Рудь', '', 'Бортник', 49.53215383548991, 28.59232751541989, '', 'Кафе на кглу', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Петр Рудь', '', 'Быкова котлярка', 50.03740292914269, 29.31841738522053, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Петр Рудь', '', 'Ванилька', 49.92120109965662, 29.00250720029602, 'Городкивка', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Петр Рудь', '', 'Ванилька', 49.9514919, 29.0871022, 'Павелки', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Петр Рудь', '', 'Ванилька степое', 50.1154033, 29.113545, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Петр Рудь', '', 'Дайнеко', 49.95763225847195, 28.86532770060532, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Генадий Рудь', '', 'Дущенко', 49.9974078, 29.0055538, 'Упетровича', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Петр Рудь', '', 'Иванченко', 49.96152769999993, 28.87279380000009, 'Маричка', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Казатин', '71b300', 'Генадий Рудь', '', 'Каминьска', 50.10728, 29.340545, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Казатин', '71b300', 'Анатолий Монак', '', 'Лозенко', 49.9909317, 29.3071567, 'Хлебныйлан', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Казатин', '71b300', 'Анатолий Монак', '', 'Людвиг', 49.90766230914378, 28.83410188362529, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Казатин', '71b300', 'Анатолий Монак', '', 'Микитюк', 49.5327333, 28.8418567, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Казатин', '71b300', 'Анатолий Монак', '', 'Михайловский', 49.73177231790935, 28.83785834883042, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Казатин', '71b300', 'Анатолий Монак', '', 'Нтчепорук', 50.1064983, 29.3137733, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Казатин', '71b300', 'Анатолий Монак', '', 'Огородничзук', 49.9618856, 28.8737351, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Казатин', '71b300', 'Анатолий Монак', '', 'Панасюк', 49.6558833, 28.8530617, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'cddc39', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Казатин', '71b300', 'Галина Монак', '', 'Прохневська', 49.9469919, 28.9220505, '', 'Продукты справа', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Казатин', '71b300', '', '', 'Слободенюк', 49.6893388, 28.6370842, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Казатин', '71b300', '', '', 'Шкарабий', 49.7044959, 28.8175273, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Казатин', '71b300', '', '', 'Шкрабий', 49.715366, 28.8312402, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', 'Ольга Мясов', '', 'Безномюк', 50.31866867981396, 28.63973062789007, '', 'Надпись магазин', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', 'Ольга Мясов', '', 'Давидюк', 50.2613131991728, 28.6761748418212, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', 'Ольга Мясов', '', 'Давидюк', 50.27539255919321, 28.66361353686466, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', '', '', 'Доброжаньска', 50.40648586866421, 28.99865984916687, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', '', '', 'Картенко', 50.2360709, 28.8559816, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', '', '', 'Курганська', 50.28770671801972, 28.89434337325916, '', 'Кава хотдог', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', 'Генадий Мясов', '', 'Куцакиавский', 50.37988674032624, 29.01947010308504, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', 'Генадий Мясов', '', 'Лавидюк', 50.59912074927432, 27.61044770479202, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Коростышев', '71b300', 'Генадий Мясов', '', 'Литвина', 50.31222612933557, 29.06019671660649, '', 'На рынке, левое. Крыло после туалета', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Коростышев', '71b300', '', '', 'Маркер 14', 50.29571162148215, 28.88706989586354, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Коростышев', '71b300', '', '', 'Осиньска', 50.34462146851575, 29.07304085791111, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Коростышев', '71b300', '', '', 'Паша Белькивци', 50.36523614414357, 28.97498466074467, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Коростышев', '71b300', '', '', 'Паша Щаниевка', 50.40650210863034, 28.89148816466331, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Анатолий Монак', '', 'Полищук', 50.28676221804249, 28.85109778493643, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Анатолий Монак', '', 'Поп', 50.2780893, 28.6573501, '', 'Выкривеньки', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Анатолий Монак', '', 'Романчук', 50.3040946, 28.8238424, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Анатолий Монак', '', 'Стекуц', 50.2695139120159, 28.79356373101473, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Анатолий Монак', '', 'Троцкий', 50.31695767519479, 29.06031612306833, '', 'Арабика лучше заехать за нее.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Светлана Монак', '', 'Харченко', 50.34226376999985, 29.07270062225695, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Светлана Монак', '', 'Хомик', 50.31851963005427, 28.63934509456158, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Светлана Монак', '', 'Шиндаптвська', 50.30237267187616, 28.82231499999762, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Коростышев', '71b300', 'Светлана Монак', '', 'Юхимчук', 50.3441535299238, 28.69056556373835, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Пулини', '71b300', 'Светлана Монак', '', 'Андриенко', 50.33248738141589, 28.4208245202899, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Пулини', '71b300', 'Светлана Монак', '', 'Башинский', 50.31271406257544, 28.44185035675764, '', 'Башигский', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Пулини', '71b300', 'Светлана Монак', '', 'Гаврилюк', 50.46327865681422, 28.26841738075018, '', 'С 10:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Пулини', '71b300', 'Светлана Монак', '', 'Звягель колиснисенко', 50.59660926468109, 27.6392563059926, '', 'Мать продуктов', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Пулини', '71b300', 'Светлана Монак', '', 'Колиснисенко', 50.46934238660032, 28.26972562819719, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Пулини', '71b300', 'Светлана Монак', '', 'Кузнецов', 50.46967280735577, 28.26492076808494, '', 'Кафе shora, жёлтый блок ларьков, крайний левый.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Пулини', '71b300', 'Светлана Монак', '', 'Шимчук', 50.57717331462359, 27.64442970092913, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n";
    private String queryPoints4 = "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Черняхов', '71b300', 'Петр Рудь', '', 'Бубало', 49.577665, 28.8343467, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Черняхов', '71b300', 'Петр Рудь', '', 'Ваеклович осынки', 50.44600259278808, 28.8201517984271, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Черняхов', '71b300', 'Петр Рудь', '', 'Вакулович головнины', 50.47611471405741, 28.8577462487499, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Черняхов', '71b300', 'Петр Рудь', '', 'Гнатенко', 49.5885817, 28.8575983, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Черняхов', '71b300', 'Петр Рудь', '', 'Давыдюк', 50.38631067944277, 28.71540684252977, '', 'В роли зоне  пооямо в конец', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Черняхов', '71b300', 'Петр Рудь', '', 'Маливанчук', 49.7192797, 28.6707903, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Черняхов', '71b300', 'Петр Рудь', '', 'Маливанчук сижа ижа', 49.7233595, 28.6730821, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('РУДЬ', 'Черняхов', '71b300', 'Петр Рудь', '', 'Маркер 12', 49.71926664653154, 28.67083534653155, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Опанасюк', 50.4552203, 28.6676184, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Остапчук', 50.39244027457309, 28.84603142738342, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Приставка', 49.5870333, 28.7877067, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Рябый', 50.44428554991242, 28.66849232465028, '', 'Ресторан', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Семенюк', 50.40565719563605, 28.80711022764444, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Сидорова', 50.47786631751846, 28.85398853570223, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Филиманкова', 50.45032759079425, 28.67160435765981, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Шевчук', 49.7637417, 28.72775, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Шостак', 49.7067383, 28.817175, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('Мясовита', 'Черняхов', '71b300', 'Генадий Мясов', '', 'Янушевский', 50.40781325384902, 28.80864679813385, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '71b300', '', NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Berdich3v', NULL, 'Светлана Монак', '', 'Точка 1', 48.8583, 2.2943997, '7fgjcd', 'sjjyh', '', 'uog fish k', '07', '00', '22', '00', '01', '00', '01', '00', NULL, 1, NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Berdich3v', NULL, 'Светлана Монак', '0777777777', 'Точка 2', 48.8583, 2.2943997, 'wttt', '', '', '', '01', '00', '01', '00', '01', '00', '01', '00', NULL, 1, NULL);\n" +
            "INSERT INTO owner_points ( organisation_name, zone, folder_color, sales_name, phone_number, point_owner, latitude, longitude, landmarks, description, phone_ambar, description_office, work_from_h, work_from_m, work_to_h, work_to_m, strike_from_h, strike_from_m, strike_to_h, strike_to_m, color, pin_icon_code, color1) VALUES ('MONACO', 'Berdich3v', NULL, 'Светлана Монак', '', 'Owner2', 48.8583, 2.2943997, 'Burger', '', '', '', '01', '00', '01', '00', '01', '00', '01', '00', NULL, 1, NULL);\n";

    private String query = "CREATE TABLE IF NOT EXISTS organisations (org_id INTEGER PRIMARY KEY AUTOINCREMENT, organisation_name VARCHAR (50) , phone_number VARCHAR (50), desc VARCHAR (300), is_active VARCHAR (10));\n" +
            "INSERT INTO organisations (organisation_name, phone_number, desc, is_active) VALUES ('MONACO', '', '', 'true');\n" +
            "INSERT INTO organisations (organisation_name, phone_number, desc, is_active) VALUES ('РУДЬ', '', '', 'false');\n" +
            "INSERT INTO organisations (organisation_name, phone_number, desc, is_active) VALUES ('Мясовита', NULL, NULL, 'false');\n" +
            //   -- Table: owner_points
            // -- Table: owner_routes
            "CREATE TABLE IF NOT EXISTS owner_routes (route_id INTEGER PRIMARY KEY AUTOINCREMENT, org_name VARCHAR (60), route_name VARCHAR (250), route_points TEXT (500));\n" +
            //  -- Table: salesman
            "CREATE TABLE IF NOT EXISTS salesman (salesman_id INTEGER PRIMARY KEY AUTOINCREMENT,  org_id INTEGER (3), salesman_name, phone_number VARCHAR (50), desc VARCHAR (450), is_active VARCHAR (10));\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (1, 'Анатолий Монак', '', 'Alkash', 'false');\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (2, 'Петр Рудь', '', '', 'false');\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (1, 'Светлана Монак', '0777777777', '', 'false');\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (3, 'Генадий Мясов', NULL, NULL, 'false');\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (2, 'Генадий Рудь', NULL, NULL, 'false');\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (3, 'Андрей Мясов', NULL, NULL, 'false');\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (3, 'Ольга Мясов', NULL, NULL, 'false');\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (2, 'Ирина Рудь', NULL, NULL, 'false');\n" +
            "INSERT INTO salesman (org_id, salesman_name, phone_number, desc, is_active) VALUES (1, 'Галина Монак', NULL, NULL, NULL);\n" +

            //  -- Table: zones
            "CREATE TABLE IF NOT EXISTS zones (zone_id INTEGER PRIMARY KEY AUTOINCREMENT,  org_id INTEGER (3), zone_name, desc VARCHAR (450), is_active VARCHAR (10));\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (1, 'Звягин', '', NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (2, 'Звягин', '', NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (3, 'Звягин', '', NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (1, 'Бердичев-1', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (2, 'Бердичев-1', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (3, 'Бердичев-1', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (1, 'Казатин', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (2, 'Казатин', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (3, 'Казатин', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (3, 'Житомир', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (1, 'Коростышев', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (2, 'Коростышев', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (3, 'Коростышев', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (1, 'Пулини', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (2, 'Пулини', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (3, 'Пулини', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (1, 'Черняхов', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (1, 'Berdich3v', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (NULL, 'Berdich3v', NULL, NULL);\n" +
            "INSERT INTO zones ( org_id, zone_name, desc, is_active) VALUES (NULL, 'Berdich3v', NULL, NULL);\n";



    public boolean insertDatasToDb(String db_name) {
        this.db_name = db_name;
        context = ThisApp.getContextApp();
//        TetDebugUtil.e(pseudo_tag, "Make insertDemoDatasToDb");
//        ShowlongLargeString.showString(query);
//        StringTokenizer st = new StringTokenizer(query, "\n");
//        int t = st.countTokens();
//        TetDebugUtil.e(pseudo_tag, "count tockens = " + t);
//        AllDatabaseController allDbController = AllDatabaseController.getSingleControllerInstance();
//        for (int i = 0; i < t; i++) {
//            String sql = st.nextToken();
//            TetDebugUtil.e(pseudo_tag, sql);
//            allDbController.executeQuery(ThisApp.getContextApp(), db_name, sql);
//        }
        boolean res = false;
        if (!addPoints(queryPoints)) {
            res = true;
        } else {
            res = false;
            TetDebugUtil.e(pseudo_tag, "ERROR with queryPoints");
        }

        if (!addPoints(queryPoints1)) {
            res = true;
        } else {
            res = false;
            TetDebugUtil.e(pseudo_tag, "ERROR with queryPoints1");
        }
        if (!addPoints(queryPoints2)) {
            res = true;
        } else {
            res = false;
            TetDebugUtil.e(pseudo_tag, "ERROR with queryPoints2");
        }
        if (!addPoints(queryPoints3)) {
            res = true;
        } else {
            res = false;
            TetDebugUtil.e(pseudo_tag, "ERROR with queryPoints3");
        }
        if (!addPoints(queryPoints4)) {
            res = true;
        } else {
            res = false;
            TetDebugUtil.e(pseudo_tag, "ERROR with queryPoints4");
        }

        if (!addPoints(query)){
            res = false;
        }

        return res;
    }

    private boolean addPoints(String query) {
        this.db_name = db_name;
        TetDebugUtil.e(pseudo_tag, "Make insertDemoDatasToDb");
        ShowlongLargeString.showString(query);
        StringTokenizer st = new StringTokenizer(query, "\n");
        int t = st.countTokens();
        TetDebugUtil.e(pseudo_tag, "count tockens = " + t);
        AllDatabaseController allDbController = AllDatabaseController.getSingleControllerInstance();
        for (int i = 0; i < t; i++) {
            String sql = st.nextToken();
            TetDebugUtil.e(pseudo_tag, sql);
            try {
                allDbController.executeQuery(context, db_name, sql);
            } catch (Exception e) {
                e.printStackTrace();
                return false;
            }

        }
        return false;
    }

}
